### ISSUE TITLE
bootstrap terraform state fails with GCP

### ISSUE THREAD

**Issue by saurabhguptasg** [pivotal-cf/pcf-pipelines#131]
The bootstrap terraform state job uses the following command:
aws --endpoint-url $S3_ENDPOINT --region $S3_REGION s3 ls "${S3_BUCKET_TERRAFORM}/"

however, using gcp interop values for endpoint and region fails; a bucket in AWS is required with AWS credentials

Also, even after doing this, the next task (create-infrastructure) stalls at check terraform state step

**Comment by krishicks** [comment]
The solution to this is to create a file:

```
cat > terraform.tfstate <<EOF
{
  "version": 3
}
```

And copy it to your bucket in S3.

**Comment by saurabhguptasg** [comment]
Hi Kris,

I tried that. It actually fails because the ListObject call throws an error
in GCP GCS

This is actually a known issue with GCS interop mode and latest AWS cli:
https://buganizer.corp.google.com/issues/31253524

The temp fix is to downgrade to awscli 1.9.9 or earlier if that is possible?

additionally, if the story has been created, for the GCP pipelines, can GCP
tools (e.g. gcloud, gsutil) be used so that compatibility issues do not
arise?

Thanks,
Saurabh

**Comment by saurabhguptasg** [comment]
Also, if this is at all helpful, the following Docker repo is available, so
it can be used as a resource instead of czero/cflinuxfs2 :
https://hub.docker.com/r/google/cloud-sdk/

and the GitHub for the Dockerfiles is here:
https://github.com/GoogleCloudPlatform/cloud-sdk-docker

Thanks,
Saurabh

**Comment by krishicks** [comment]
I don't have access to that buganizer link.

Presently we don't support Google Cloud Storage in the pipelines. As I said we do not test against it.

If you are unable to add the terraform.tfstate file as I described above and have the s3-resource use it successfully, which I believe you said was the case, further modification to the pipeline would be necessary to get it to work, for example by using https://github.com/frodenas/gcs-resource instead of the s3 resource.

If you'd like to hop on a Zoom meeting, to talk more, find me on https://slack.cloudfoundry.org/.

**Comment by krishicks** [comment]
Given we require a GCS storage access key for the blobs, we should probably switch to using GCS for the GCP pipeline to store terraform state, too. I had forgotten that the GCP install-pcf pipeline is using GCS.

**Comment by saurabhguptasg** [comment]
Hi all,

I fixed this and checked it in using the GCS resource

The repo is at:
https://GitHub.com/gcpce-03/pcf-pipelines
Branch: sg-v0.15.1-rc.20

There were a few other tweaks (change ntp server, dns defaults, etc)

**Comment by krishicks** [comment]
The switch to use GCS for the GCP pipeline is in v0.15.1+.

**Comment by saurabhguptasg** [comment]
Awesome! Thanks!
