### ISSUE TITLE
[Azure] generate keyword in params.yml fails pcf_ert_ssl_cert and pcf_ert_ssl_key generation

### ISSUE THREAD

**Issue by dwntwnbrown** [pivotal-cf/pcf-pipelines#182]
The current script `/tasks/config-ert/task.sh` does not support the `generate` keyword that is documented in the `azure/params.yml` file:

```...
# ERT Cert & Key , if the string 'generate' is passed, pipeline will autogen certs
pcf_ert_networking_pointofentry: "haproxy" #This is set to HAProxy for now as Azure load balancer does not support external SSL termination now. If Azure adds suport for that, you may change it to a different value in future.
pcf_ert_ssl_cert: |
  CHANGEME
pcf_ert_ssl_key: CHANGEME
...
```

`/tasks/config-ert/task.sh`
```
if [[ -z "$SSL_CERT" ]]; then
  domains=(
    "*.${SYSTEM_DOMAIN}"
    "*.${APPS_DOMAIN}"
    "*.login.${SYSTEM_DOMAIN}"
    "*.uaa.${SYSTEM_DOMAIN}"
  )

  certificates=$(generate_cert "${domains[*]}")
  SSL_CERT=`echo $certificates | jq --raw-output '.certificate'`
  SSL_PRIVATE_KEY=`echo $certificates | jq --raw-output '.key'`
fi

if [[ -z "$SAML_SSL_CERT" ]]; then
  saml_cert_domains=(
    "*.${SYSTEM_DOMAIN}"
    "*.login.${SYSTEM_DOMAIN}"
    "*.uaa.${SYSTEM_DOMAIN}"
  )

  saml_certificates=$(generate_cert "${saml_cert_domains[*]}")
  SAML_SSL_CERT=$(echo $saml_certificates | jq --raw-output '.certificate')
  SAML_SSL_PRIVATE_KEY=$(echo $saml_certificates | jq --raw-output '.key')
fi
```

The `tasks/configure-ert/task.sh` that is used by the AWS pipeline supports the generate keyword with the following:

`if [[ ${pcf_ert_ssl_cert} == "" || ${pcf_ert_ssl_cert} == "generate" ]]; then`

**Comment by abbyachau** [comment]
thanks @dwntwnbrown, what version of pcf-pipelines are you using? and was it obtained via github or pivnet? thanks!

**Comment by dwntwnbrown** [comment]
Github, latest master.

**Comment by abbyachau** [comment]
hey @dwntwnbrown thanks for raising this issue. we've looked into this and it appears our pipeline is inconsistent in how we auto generate certs. for instance, the aws and vsphere currently mentions leaving the field blank in order to generate certs. gcp mentions setting the field to "generate". standardizing these pipelines is something we hope to get to at some point but it is not a priority right now.  i've created this tracker issue (https://www.pivotaltracker.com/story/show/150995888) to record this for future consideration but i'm closing this issue because we've updated the azure params by clarifying that the field needs to be blank. thanks again.
