### ISSUE TITLE
upload-and-stage-err fails with ERROR: release not found

### ISSUE THREAD

**Issue by nebhale** [pivotal-cf/pcf-pipelines#209]
This morning, after the latest round of ERT updates, all four of my `upgrade-ert` pipelines have failed with the same error message, `ERROR: release not found` when attempting to get the `pcs-pipelines-tarball`, version `v0.19.0`.

![ea8e22b9-5379-49da-9345-7b8679e2789d](https://user-images.githubusercontent.com/60754/32000731-8b6da1b2-b94c-11e7-8918-4045d93cecac.jpeg)

**Comment by abbyachau** [comment]
Hi @nebhale, we've pull v19 pcf-pipelines due to a bug in the vSphere install-pcf pipeline wipe-env job. We are working releasing as soon as possible. For now, please use pcf-pipelines v18. Do not hesitate to reach out if you have any questions.

**Comment by nebhale** [comment]
Unfortunately, I can’t rollback to v18 because I required [this change](https://github.com/pivotal-cf/pcf-pipelines/commit/21f04dd0f3499d776259e8f744c425918ef9a0e7) in order to keep PCF 1.12 up to date.

I think, even more fundamentally, that you’ve made a mistake removing a previously released piece of software.  I’m now currently in a no-man’s-land where I’ve taken a released piece of software, and deployed it.  It’s worked fine for me until now (it’s how I managed to get onto 1.12.4, as the fix allowed) and yet, through no action on my part, that same code no longer works.  As I don’t use the dangerous job that caused you to revoke the release, you’ve effectively broken the system I use to keep my systems secure, for no benefit to me.

There is a reason that software repositories (like NPM, Maven Central, etc.) are immutable.  Removing this release and breaking running code has seriously impacted the trust I have in the product.  I am comfortable that any upgrade that I do might not work and take down my pipelines.  However I now have to be worried that at any moment, software that has worked up to that point will break because my vendor has removed a dependency that the software relies on.

**Comment by abbyachau** [comment]
Hi @nebhale, sorry about the delay, I've just seen this. Apologies about this situation. You are right, the bug we found did not affect all customers - only those on vSphere using the install and upgrade-ops-manager pipelines. We ascertained that the bug was severe enough (if the `wipe-env` job was triggered, vms which you did not intend to delete may have been deleted by mistake) to merit this action but it unfortunately had consequences for other users. We have now prioritised stories in our backlog which will allow our team to more frequently and robustly publish a release. And we will be making sure that our strategy if such an event occurs again, will be a much quicker response moving forward. I'll be reaching out to you to follow-up on this issue but please let us know if you have any further thoughts on the matter. Thanks.

**Comment by nebhale** [comment]
Sounds good.  I look forward to the discussion.
