### ISSUE TITLE
Error loading key "/tmp/git-resource-private-key": invalid format

### ISSUE THREAD

**Issue by akamalov** [pivotal-cf/pcf-pipelines#344]
**Environment:**

```
PCF: 2.0.16
PCF-Pipelines-Release: 0.23.6
Concourse: 3.14.0
```

Trying to upgrade stemcells. Unpausing a pipeline is displaying the following error:

**Error:**
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Error loading key "/tmp/git-resource-private-key": invalid format
```

**Screenshot**

![image](https://user-images.githubusercontent.com/7885257/42342558-6f4753fe-8064-11e8-96b0-9604f391d127.png)

My settings are as follows:
```
pcf_pipelines_project_url: https://github.com/pivotal-cf/pcf-pipelines.git
git_private_key: "" 
maestro_project_url: ssh://git@<internal.bitbucket.site>l/cf/pcf-pipelines-maestro.git 
git_maestro_private_key: |
  XXXXXXXXXXXXXXXXXXXX...
```
Key for ```git_maestro_private_key``` worked for the other pipelines without a problem.

**Comment by akamalov** [comment]
Any update on this ticket?

**Comment by calebwashburn** [comment]
Please refer questions using maestro to the following repo (https://github.com/pivotalservices/pcf-pipelines-maestro)  As pcf-pipelines has no knowledge of maestro so likely an incompatiblity with maestro/tile/pipeline version.

**Comment by lsilvapvt** [comment]
@akamalov That stemcell upgrade pipeline does not come from `pcf-pipelines`, it comes from the maestro's repository (https://github.com/pivotalservices/pcf-pipelines-maestro/blob/master/pipelines/utils/stemcell-adhoc-upgrade.yml). That pipeline has not been kept up-to-date since stemcell upgrade has been embedded as part of the standard `upgrade-tile` pipeline, so I would not recommend its usage at the moment. I agree that there is the case for an adhoc stemcell upgrade pipeline in some cases, but that pipeline requires some re-work and it may take some time for me to do it given the priorities of other required work. 
PR's to the maestro community repo are welcome in case you end up solving the problem for that pipeline. For future Maestro issues, please feel free to open the issues directly on the Maestro repository. I will be glad to re-direct the issues to `pcf-pipelines` as appropriate. Regards.
