### ISSUE TITLE
Azure opsman will not allow ssh access until the config is reset

### ISSUE THREAD

**Issue by gondoi** [pivotal-cf/pcf-pipelines#350]
## Issue

When using `install-pcf` on Azure from the `master` branch and after opsman has been built, ssh access to the server is broken. The only way to get access is to log into the azure portal and "reset ssh configuration" for the opsman vm.

## Context

Unable to ssh into opsman to interact with bosh if ports are locked down.

### Expected result

SSH works as expected with the private key.

### Current result

When running `ssh terraform@opsman -i ~/.ssh/opsman_key.pub` results in public key denied. Even when resetting through Azure portal, it never works. The only way to get access is to log into the azure portal and "reset ssh configuration" for the opsman vm.

## Steps to Reproduce

Run `install-pcf` pipeline and attempt to ssh into opsman with the provided key. Reset configuration and try again.

**Comment by calebwashburn** [comment]
The latest stable release comes from network.pivotal.io.  (https://network.pivotal.io/products/pcf-automation) if you don't have access you need to request this via your sales organization.  That being said, I think the problem is you are passing the public key `.pub` instead of private key.  This should match what is in the parameter `pcf_ssh_key_priv:` (https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/azure/params.yml#L198)

**Comment by gondoi** [comment]
I'm passing in both and they work and match. I've tested on other servers. Although, I have come to find out it's not related to this pipeline, but the image for opsman itself. I upgraded the opsman server and after the new image boots up, ssh no longer works, even when attempting to reset the key through Azure. There is a diff and there are a lot of options removed after resetting the configuration (which allows access via the original key).
