### ISSUE TITLE
task failure import-opsmgr-settings

### ISSUE THREAD

**Issue by sonmacharius** [pivotal-cf/pcf-pipelines#384]
https://github.com/pivotal-cf/pcf-pipelines/blob/40733516f1e961ea5768d7fae1be4a029fda6764/tasks/import-opsmgr-settings/task.sh#L35

--decryption-passphrase "${OPSMAN_PASSPHRASE}"
needs to be put in front of import-installation for the om-linux command to execute properly or you will get 

could not execute "import-installation": the global decryption-passphrase argument is required for this command

suggest moving line 35 before 33.

**Comment by nebhale** [comment]
Note that this is the same bug as is PR'd in #376.

**Comment by jtarchie** [comment]
This is not the same issue as the PR #376.
The proposed solution in the PR will not work for the version of `om` that is currently installed on the docker image.

The issue that this person is experiencing is an issue with `om`.
It has a [second issue](https://github.com/pivotal-cf/om/issues/361) reported on `om`.

**Comment by jtarchie** [comment]
The change that needs to be made to the task.

```diff
@@ -31,8 +31,8 @@ function main() {
       --skip-ssl-validation \
       --request-timeout 86400 \
       import-installation \
-      --installation "${cwd}/opsmgr-settings/${OPSMAN_SETTINGS_FILENAME}" \
-      --decryption-passphrase "${OPSMAN_PASSPHRASE}"
+      --decryption-passphrase "${OPSMAN_PASSPHRASE}" \
+      --installation "${cwd}/opsmgr-settings/${OPSMAN_SETTINGS_FILENAME}"
  }

  main "${PWD}"
```

**Comment by kcboyle** [comment]
This is being fixed because this is a _breaking change_ for current pipelines.

This will be included in the next (last) release of pcf-pipelines.  **This feature has _not_ been tested by CI, nor will it be. Use this commit and the corresponding release at your own risk.**

In the future, please use [platform-automation](network.pivotal.io/products/platform-automation) for all your automation needs. [Pivotal Documentation](docs.pivotal.io/platform-automation)
