### ISSUE TITLE
Ops Mgr upgrade has risk of loosing ops mgr settings.

### ISSUE THREAD

**Issue by haydonryan** [pivotal-cf/pcf-pipelines#65]
Since the ops mgr settings are not persisted/backed up as part of the pipeline, if the concourse worker container goes away during the deploy for any reason, then there is the risk that you will not be able to put the settings back into ops mgr.

Can we maybe have a backup done as part of the pipeline to s3? or an option for something like that?

**Comment by krishicks** [comment]
We should add some example operations files for this purpose. @haydonryan if you were able to contribute that it would be appreciated.

We'd want to add a new resource and then add a new task to the job that does the export of settings to put it elsewhere.

I'm not sure how we'd manage that resource, though, because each time the pipeline runs we'd be adding multiple GB of data to that S3 store. Maybe we consider that out of scope and just put a warning that the S3 storage used by the export will need to be groomed via some mechanism.

**Comment by svrc-pivotal** [comment]
I'm not sure you'd lose the settings as the old ops man VM isn't usually trashed, it's just shut down.  a pipeline failure would require a manual shutdown of the new/incomplete ops man and restart of the old one.

but otherwise, +1 if anything to speed up the pipeline after export (not requiring the 10 minute+ wait for to rerun the export every time)

perhaps you'd do a "check" on that cached resource to see if it exists for the version we want and at the sha1 we want (which we would know from Pivnet).

**Comment by haydonryan** [comment]
@svrc-pivotal Turns out you are correct. I took this as an issue from the customer.  We can close it, if everyone wants. I still like the idea of persisting the settings, so that if an ops mgr does fail to come up, it's just a case of re-running the job vs manual intervention.

**Comment by krishicks** [comment]
I also like the idea of persisting settings, but it'd need to be done via yaml-patch ops files. I'll close this for now but if you'd like to do a PR for some ops files that do this that would be great.
