### ISSUE TITLE
gcp bucket names must be globally unique

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [pivotal-cf/pcf-pipelines#90]
I got it to work by changing this value:
https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/gcp/params.yml#L9

Should that be a `CHANGEME`?

**Comment by xtreme-gavin-enns** [comment]
This might instead have to do with failure to roll back

**Comment by xtreme-gavin-enns** [comment]
![screen shot 2017-05-25 at 11 14 40 am](https://cloud.githubusercontent.com/assets/1178694/26456545/629835c4-413b-11e7-905d-f83397653819.png)

**Comment by krishicks** [comment]
Yep, that should be a CHANGEME.

**Comment by krishicks** [comment]
Actually, I was thinking it was for something else.

`terraform_prefix` is something that's used as a prefix for all of the resources that are managed by Terraform. It has nothing, or should have nothing to do with a GCP bucket name.

Your error is due to something else. I just did a lot of fixes to the GCP pipeline; I'll ask you to update and re-run it and see if you still have the problem. I'll close this issue for now; if it's still a problem for you please re-open it.

**Comment by krishicks** [comment]
Also, the `rollback` job has been removed from the pipeline and the state is handled in a different way than previously. If you put the file in your S3 bucket at the root (instead of in the `bucket/terraform` folder), and rename it to `terraform.tfstate` (no version), it should pick it up automatically and allow you to run `create-infrastructure` again.
